language: cpp

compiler:
  - gcc

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

install:
  - sudo apt-get install --allow-unauthenticated -qq libboost-dev clang-3.6 libclang-3.6-dev python-pip
  - sudo pip install lit

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_CXX_COMPILER=clang++-3.6 -DCPACK_GENERATOR="TGZ;DEB" ..
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
  - make package

after_success:
  - sudo dpkg -i ./constantine-*.deb
